/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tinymonster_ffmpegstudy1_FFmpegDecode */

#ifndef _Included_com_tinymonster_ffmpegstudy1_FFmpegDecode
#define _Included_com_tinymonster_ffmpegstudy1_FFmpegDecode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tinymonster_ffmpegstudy1_FFmpegDecode
 * Method:    Decode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_tinymonster_ffmpegstudy1_FFmpegDecode_Decode
  (JNIEnv *, jclass);

/*
 * Class:     com_tinymonster_ffmpegstudy1_FFmpegDecode
 * Method:    DecodeFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_tinymonster_ffmpegstudy1_FFmpegDecode_DecodeFile
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
